language: python
python:
  - "3.4"
# command to install dependencies
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install texlive-full
    - sudo apt-get install poppler-utils 
    - sudo apt-get install gnome-calculator 
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
