language: python
python:
  - "3.4"
# command to install dependencies
before_install:
    - sudo apt-get -qq update
    - chmod +x install.sh
    - ./install.sh
install:
    - pip install -r requirements.txt
# command to run tests
script: 
    - python3 -m pytest --cov-report term-missing --doctest-modules --cov=. test
    - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN coveralls

after_failure:
  # I'm debugging putnam, and this should tell me what problem it's choking on
  - cat default.tex
