dist: trusty
sudo: required
language: python
python:
  - "3.4"
# command to install dependencies
before_install:
    - sudo apt-get -qq update
    - chmod +x install.sh
    - sudo ./install.sh
install:
    - pip install -r requirements.txt
# command to run tests
script: 
    - python3 -m pytest --cov-report term-missing --doctest-modules --cov=. test
    - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN coveralls
