language: python
python:
  - "3.4"
# command to install dependencies
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install texlive
    - sudo apt-get install poppler-utils
install: 
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pytest pytest-cov
# command to run tests
script: 
    - python3 -m pytest test
after_sucess:
    - coveralls
