language: python
python:
  - "3.4"
# command to install dependencies
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install texlive
    - sudo apt-get install poppler-utils 
    - sudo apt-get install gcalctool 
    - sudo apt-get install pylint
install: "pip install -r requirements.txt && pip install nose pylint"
# command to run tests
script: "nosetests && pylint app.py"
