dist: trusty
sudo: required
language: python
python:
  - "3.4"
services:
  - docker
# command to install dependencies
before_install:
  - docker pull wgma/pokemonshowdownbot
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "python3 -m pytest --pep8 --cov-report term-missing --doctest-modules --cov=. test"

install:
    - pip install -r requirements.txt
# command to run tests
script: 
    - python3 -m pytest --pep8 --cov-report term-missing --doctest-modules --cov=. test
    - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN coveralls
