dist: trusty
sudo: required

language: python
python:
  - "3.4"

services:
  - docker

install:
    - docker build -t quadbot --cache-from wgma/quadbot-base:latest .
script: 
    - docker run --rm -it -e IMGUR_API="${IMGUR_API}" -e COVERALLS_REPO_TOKEN="${COVERALLS_TOKEN}" quadbot bash -c "python3 -m pytest --pep8 --cov-report term-missing --doctest-modules --cov=. test && coveralls"
