language: python
python:
  - "3.4"
# command to install dependencies
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install texlive
    - sudo apt-get install poppler-utils 
install: 
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests
script: 
    - pytest test/*
    - coverage run
after_sucess:
    coveralls
